### ISSUE TITLE
config.properties missing

### ISSUE THREAD

**Issue by fjlopez** [IAAA-Lab/UNIZAR-BuildingsApp#7]
The server app expects the file `config.properties` at the path `src/main/resources`. This file should be present or well documented in the `README.md`.

**Comment by daniegarcia254** [comment]
Fixed with https://github.com/daniegarcia254/UNIZAR-BuildingsApp/commit/77a823f517b2a46d2ff1e1f82cec7ede89c7cf94

**Comment by daniegarcia254** [comment]
Fixed with https://github.com/daniegarcia254/UNIZAR-BuildingsApp/commit/77a823f517b2a46d2ff1e1f82cec7ede89c7cf94

**Comment by daniegarcia254** [comment]
Off topic, but related with the _config.properties_ file.

@fjlopez I have a problem when it comes to upload files to the server with size greater than 1MB. It throws me an error:

`exception is org.springframework.web.multipart.MultipartException: Could not parse multipart servlet request; nested exception is java.lang.IllegalStateException: org.apache.tomcat.util.http.fileupload.FileUploadBase$FileSizeLimitExceededException: The field file exceeds its maximum permitted size of 1048576 bytes.`

I've tried some solutions I've find looking through Google:
- Add to config.properties:[http://stackoverflow.com/a/27062232/3593914](http://stackoverflow.com/a/27062232/3593914)
- Use XML: [http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#mvc-multipart](http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#mvc-multipart)

But none of theem seems to work, still receiving the error.

As I know you're very acquainted with Spring Framework, do you of any valid solution?

**Comment by fjlopez** [comment]
I copy the identified issue in #10 and close this bug.
